algoritmo "Contar até X"
// Função : contar de 0 ao numero que o usuario desejar
// Autor : RVVA
// Data : 06/01/2022
// Seção de Declarações 
var
contador, usu: inteiro
inicio
      escreva("Até que valor você deseja contar? ")
      leia(usu)
    contador <- 0
    enquanto (contador <= usu) faca
             escreval(contador)
             contador <- contador + 1
    fimenquanto
    escreval("Terminei de contar")
fimalgoritmo
