algoritmo "semnome"
// Função :
// Autor :
// Data : 09/01/2022
// Seção de Declarações 
var
   num, cont, contf, soma: inteiro
inicio
    escreva ("Quantos numeros deseja somar? ")
    leia (cont)
    
    enquanto cont >= 1 faca
    escreva("Insira os numeros que deseja somar: ")
    leia (num)
    
    se num = 1111 entao
       interrompa
    fimse
    soma <- soma + num
    cont <-  cont - 1
    fimenquanto
    
    escreva("A soma dos numeros digitados é igual a: ", soma)
fimalgoritmo



