algoritmo "semnome"
// Função :
// Autor :
// Data : 11/01/2022
// Seção de Declarações 
var
   x, y: inteiro
procedimento soma(A, B: inteiro)
inicio
      A <- A + 1
      B <- B + 2
      escreval("Valor de a = ", A)
      escreval("Valor de b = ", B)
      escreval("Soma de a+b = ", A+B)
fimprocedimento
inicio
      x <- 4
      y <- 8
      soma(x, y)
      escreval("valor de X = ",x)
      escreval("Valor de Y = ", y)


fimalgoritmo
